on:
  workflow_dispatch:

jobs:
  install:
    uses: carvalheiro/TESTE-GH-RELEASE/.github/workflows/reusable_workflow.yml@main
    with:
      environment: deuboameurei
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo {{ github.sha }}
    
      

