
name: Pull Request Checks

on:
  pull_request_review:
    types: [submitted]
  pull_request_target:
    types: [labeled]
  pull_request:
    types: [synchronize]

jobs:
  install:
    if: github.envet.label.name == 'ci:run' || github.envet.label.name == 'ci:all'
    runs-on: ubuntu-latest
    name: Install
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env: 
          TESTE_1: ${{ github.event.label.name }}
          TESTE_2: ${{ github.event_name }}
          TESTE_3: ${{ github.event.review.state }}          
        run: |
          echo $TESTE_1,
          echo $TESTE_2,
          echo $TESTE_3
  lint:
    name: Lint
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: ESLint
        run: echo Rodou o Lint
  jest:
    name: Automated Tests
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Automated Tests
        run: echo Rodou o Tests
  ready_to_merge:
    name: Ready to Merge
    runs-on: ubuntu-20.04
    if: always() # always run, so we never skip the check
    needs: [install, lint, jest]
    env:
      PASSED: ${{ needs.install.outputs.success && needs.lint.outputs.success && needs.jest.outputs.success }}
    steps:
      # pass step only when output of previous after-shards job is set
      # in case at least one of the shard fails, after-shards is skipped
      # and the output will not be set, which will then cause the ci job to fail
      - run: |
          if [[ $PASSED == "true" ]]; then
            echo "Tests has passed"
            exit 0
          else
            echo "Tests has failed"
            exit 1
          fi
      
    
  
